#How many blocks should be mined at once?
#Range: 2 ~ 8192
blocklimit = 16
#How much xp points will be used for one block/executed action (see xpUsageType)
#Range: 0 ~ 1000
xpUsage = 0
#How much xp points will be used for one block
#Allowed Values: PER_BLOCK, PER_ACTION
xpUsageType = "PER_ACTION"
#How much food exhaustion will caused by one block
#Range: 0.0 ~ 1000.0
hungerUsage = 0.005
#If set to true, you need the correct tool to break the blocks.
requiresCorrectTool = true
#If set to true, blocks will only be found on the 6 sides on each block.
#It does not mean that only the 6 blocks around will be mined, but only these will be added to the list which should be mined.
disableDiagonals = false
#If set to true, the player will be able to change shapes.
allowShapeSelection = true
#If user helds no item, it will not multi-mine
fistForbidden = false
#Inverts the block tag 'excavar:forbidden_blocks' to allow only these
invertForbiddenTag = false
#Defines which blocks can be mined with Excavar
#Allowed Values: ORES, LOGS, ORES_AND_LOGS, ALL
allowedBlocks = "ALL"
#A list of tools which aren't allowed.
#You can use "*" to define a wildcard, e.g. "minecraft:*_pickaxe" will add all vanilla pickaxes to the list.
forbiddenItems = ["botania:terra_axe", "botania:terra_pick"]

